using System;

namespace Dot.Net.DevFast.Extensions.Ppc
{
    /// <summary>
    /// Feed generated by producers (to be consumed by consumers).
    /// </summary>
    /// <typeparam name="T">feed Data type</typeparam>
    public interface IProducerFeed<T>
    {
        /// <summary>
        /// Provides the data instances generatd by Producer(s) and returns true. 
        /// False is returned when no more data is available and never be available in future.
        /// </summary>
        /// <param name="data">Produced data instance, if any</param>
        bool TryGet(out T data);
    }

    /// <summary>
    /// Feed generated for consumers (to be populated by producers).
    /// </summary>
    /// <typeparam name="T">feed Data type</typeparam>
    public interface IConsumerFeed<in T>
    {
        /// <summary>
        /// Adds an item in the feed to be consumed by consumers observing the feed.
        /// </summary>
        /// <param name="item">item to add</param>
        void Add(T item);
    }

    internal interface IPpcFeed<T> : IConsumerFeed<T>, IProducerFeed<T>, IDisposable
    {
    }
}